### PR TITLE
Start rewriting docs towards `queries`

### LINKED ISSUE #118: Write a doc block for the queries api
Part of #110 

Based on the API described in the tests [here](https://github.com/ReactTraining/react-media/pull/72/files).

### PR DESCRIPTION
**Pull request by tstirrat15**
Fixes #118 

## Motivation
This is one of the tasks before a v2 master release.

## Discussion

- [ ] What is the behavior of `queries` plus child components (i.e. not a child function, but rather child JSX)? Must all queries match, or is it at least one query matches? [This bit](https://github.com/ReactTraining/react-media/pull/72/files#diff-9905d833ff7008966abee8d1553559f4R78) seems to indicate that it's `some` as opposed to `every`.
- [x] Waiting to see whether `query` will exist alongside `queries`

### CODE REVIEW

**Comment by edorivai** [comment]
> What is the behavior of queries plus child components (i.e. not a child function, but rather child JSX)?

Good question, didn't even think about this actually :thinking:. Actually, the same goes for the `render` prop... @mjackson have you got an opinion about this?

**Comment by gribnoysup** [comment]
Maybe my two cents on the topic will help a little as I am responsible for the `queries`

First of all, I tried to preserve the previous behaviour of the render method as much as possible following the discussion in https://github.com/ReactTraining/react-media/issues/69

> What is the behavior of `queries` plus child components ...

This was the "biggest" change in the PR in my opinion. 

With `query` it was pretty straightforward what to do there for the render: if it matches, render children, if its not, skip rendering. Now when the matches are an object, I decided to go with render even if one matches, as otherwise it is seems pointless to have queries in the first place. 

You also can have a case where none of them will match at the same time ever (imagine mixing `{min,max}-width` for example), so nothing will be rendered ever. I thought that those cases could be really frustrating for some library users.

Hope this clarifies the decision behind `some` instead of `every`

Now, with this approach, there is still an issue. If we are rendering children for `some` cases, how to make children aware of the reason? We can't send those props to a component when it is a DOM element, this will cause React to print nasty warnings (and for a good reason). So instead I decided to pass `matches ` as a prop to `children` component, but only if it is NOT a DOM element

> Waiting to see whether `query` will exist alongside queries

Per initial comment in https://github.com/ReactTraining/react-media/issues/69#issue-242544489 @mjackson suggested "to release a 2.x that removes the <Media query> prop and uses <Media queries> instead"

Hope that helps!

**Comment by edorivai** [comment]
> @mjackson suggested "to release a 2.x that removes the <Media query> prop and uses <Media queries> instead"

Yeah, I'm aware of this, and when I first read it, I thought it made a lot of sense. However, I came to realize that - at least for my own code bases - this would require quite a lot of refactoring if I'd want to upgrade to v2, without really getting any benefit since most of the time I'm only specifying a single query.

I would actually expect the single-query case to be the most common one, by a significant margin. So given both the smooth transition path, as well as a convenience API for the single-query case, I thought it'd be worth it to consider leaving the `query` prop alongside `queries`.

**Comment by tstirrat15** [comment]
Meaning we'd need a PR against the work in #72 to preserve that behavior, yeah?

**Comment by edorivai** [comment]
@tstirrat15 Yeah, that's right

**Comment by tstirrat15** [comment]
Shall I update this towards #123, or do you want to get that merged first?

**Comment by edorivai** [comment]
I've just merged #123 into `next`, and plan to merge `next` into `master` soon. So I guess you could rebase on `next`.

**Comment by tstirrat15** [comment]
@edorivai have another look. I added a section to Basic Usage with `query` as an alternative, added a section about the salient differences between the two props, and moved the Render Props documentation to be children of the separate `query` and `queries` documentation. It's maybe a little redundant, but I think it's comprehensive.

**Comment by edorivai** [comment]
:+1: Love it!

**Pull request merged**
