### PR TITLE
Update queries test

### PR DESCRIPTION
**Pull request by VinSpee**
update test / readme to cover use of `queries` on attributes as mentioned in #38.

### CODE REVIEW

**Comment by VinSpee** [comment]
Gah didn't realize we're not transpiling tests. update coming

**Comment by mjackson** [comment]
Our tests do run through babel but we don't include the `babel-polyfill` which I think you'd probably need for the `Array.from` to work.

**Comment by VinSpee** [comment]
No problem, easy enough to just use the `classList.contains` method. Thanks!

**Comment by mjackson** [comment]
Thanks again, @VinSpee

**Pull request merged**
