### PR TITLE
Add support for mocking

### PR DESCRIPTION
**Pull request by RobertBorg**
I wanted to be able to mock for testing / showcasing components in a specific setting.

### CODE REVIEW

**Comment by RobertBorg** [comment]
do you want to work around the lack of includes or add babel-polyfill to karma webpack conf?

**Comment by mjackson** [comment]
Creating a `mockedMedia` object that you run your queries against seems like a lot of work for creating a mock to test against. Isn't there a more straightforward way you can build your test?

**Comment by RobertBorg** [comment]
For showcasing i guess i could use a fixed width iframe? would that work? but server side rendering to match the guessed device size? i don't see how the current implementation will simulate matching all queries, by adding this one would be able to control what is actually being rendered.

**Comment by mjackson** [comment]
For showcasing you can use Chrome DevTools to make the browser match whatever media query you'd like. For server-side rendering, we could possibly add a `defaultMatches` prop to initialize `this.state.matches`. In any case, I think a mock is too much work.

**Comment by RobertBorg** [comment]
ok say you have a PageComponent that  has components using <Media> to do conditional rendering.

To pass what to match and what not to match u'd either need to pass the props deeply through the tree, use redux connect HOC or use the context like i did here. After that is solved, you'd still need to implement the same logic as i did here to see if they actually match. e.g you say that we should default init matches to a value, which value? depends on the query and the current guessed screen size. I can use chrome dev tools to test a component in any setting i want, but not to showcase with something like react-storybook

**Comment by RobertBorg** [comment]
App = ({currentRoute}) => <AppWrapper>{currentRoute}</AppWrapper>

MediaMobile = ({children}) => <Media query={{maxWidth:500}}>{children}</Media>

MediaTabletUp = ({children}) => <Media query={{minWidth:501}}>{children}</Media>

SomeComponent = ({...someProps}) => (<div><MediaMobile>mobile</MediaMobile><MediaTabletUp>tabletUp</MediaTabletUp></div>)

SomeRoute = () =>  <SomeComponent/>

**Pull request closed without merging**
